// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $("#no8").click(function() {
      return $("p[class^=pos]", this).toggleClass("active");
    });
    return $("#index3 a").click(function() {
      var _bg, _href;
      _href = $(this).attr("href");
      $("div[id^=page]").removeClass("active");
      $("#" + _href).addClass("active");
      _bg = $("#" + _href).css("background-image");
      $("body").css("background-image", _bg);
      return false;
    });
  });

}).call(this);
